export const organizations = [
  { _id: "org_000", name: "Google", blogCount: 7 },
  { _id: "org_001", name: "Amazon", blogCount: 2 },
  { _id: "org_002", name: "Atlassian", blogCount: 2 },
  { _id: "org_003", name: "FactSet", blogCount: 1 },
  { _id: "org_004", name: "Razorpay", blogCount: 1 },
  { _id: "org_006", name: "Cisco", blogCount: 1 },
  { _id: "org_008", name: "Oracle", blogCount: 1 },
  { _id: "org_009", name: "BrowserStack", blogCount: 1 },
  { _id: "org_0012", name: "VMWare", blogCount: 1 },
  { _id: "org_0013", name: "Ivy", blogCount: 1 },
  { _id: "org_0015", name: "Toptal", blogCount: 1 },
  { _id: "org_0017", name: "PhonePe", blogCount: 1 },
  { _id: "org_0018", name: "Apple", blogCount: 1 },
  { _id: "org_0019", name: "Infosys", blogCount: 1 },
  { _id: "org_0020", name: "Mercedes Benz", blogCount: 1 },
  { _id: "org_0021", name: "Coupang", blogCount: 1 },
  { _id: "org_0022", name: "Microsoft", blogCount: 1 },
  { _id: "org_0024", name: "Uber", blogCount: 1 },
];
